### ISSUE TITLE
Package stopped working after update to chefdk 2.0.28

### ISSUE THREAD

**Issue by lucasslima** [mattstratton/linter-cookstyle#9]
Hi,

The package is throwing errors after I updated my chefdk to 2.0.28.

This is the message I get:

```
[Linter] Error running cookstyle Error: -s/--stdin requires exactly one path.
/opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/rubocop-0.49.1/lib/rubocop/options.rb:30:in `parse'
/opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/rubocop-0.49.1/lib/rubocop/cli.rb:23:in `run'
/opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/rubocop-0.49.1/bin/rubocop:13:in `block in <top (required)>'
/opt/chefdk/embedded/lib/ruby/2.4.0/benchmark.rb:308:in `realtime'
/opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/rubocop-0.49.1/bin/rubocop:12:in `<top (required)>'
/opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/cookstyle-2.0.0/bin/cookstyle:13:in `load'
/opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/cookstyle-2.0.0/bin/cookstyle:13:in `<top (required)>'
/opt/chefdk/bin/cookstyle:263:in `load'
/opt/chefdk/bin/cookstyle:263:in `<main>'
    at /home/lucas/.atom/packages/linter-cookstyle/lib/index.coffee:48:15
```
Any way i can fix this?

**Comment by nweddle** [comment]
Looks like this is caused by the version of rubocop (0.49.1) that was included in ChefDK 2.0.13
See: https://github.com/bbatsov/rubocop/pull/4226

**Comment by mattstratton** [comment]
This has been published to the package repository, so feel free to update!

**Comment by lucasslima** [comment]
Awesome! Thanks for the quick resolution!
